#@server = https://piero-rodriguez-cansaya-fictional-pxqqq6v975x2rv46-8080.preview.app.github.dev
@server = https://ec3-2hsp.onrender.com
@apiserver = {{server}}/api/Instrumento
###
GET {{server}}/
###
GET {{server}}/codigo
###
GET {{server}}/nombre-completo
###
GET {{apiserver}}/listar
###
POST {{apiserver}}/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=tambor
###
DELETE {{apiserver}}/eliminar
Content-Type: application/x-www-form-urlencoded

id=2